#!/bin/bash

# resolve links - $0 may be a softlink
SOURCE="$0"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  echo "loop source: $SOURCE"
  # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
PRGDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
BASEDIR="$( cd -P "$PRGDIR"/.. && pwd )"

exec java -jar "$BASEDIR"/cleave-${project.version}.jar "$@"
